"""autogenerate_votes_test_table

Revision ID: 0cb569b67f42
Revises: ebf8d2653fed
Create Date: 2026-01-28 15:27:09.040667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cb569b67f42'
down_revision: Union[str, Sequence[str], None] = 'ebf8d2653fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes_test',
    sa.Column('post_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_ID'], ['posts_test.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_ID'], ['users_test.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_ID', 'user_ID')
    )
    op.alter_column('posts_test', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_test', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_table('votes_test')
    # ### end Alembic commands ###
